export const demoSeedData = [
  // 15 days ago
  {
    symptom_name: "Headache",
    icon_name: "Brain",
    severity: 7,
    notes: "Dull ache behind the eyes most of the afternoon.",
    _seedDaysAgo: 15,
  },
  {
    symptom_name: "Headache",
    icon_name: "Brain",
    severity: 8,
    notes: "",
    _seedDaysAgo: 15,
  },
  {
    symptom_name: "Headache",
    icon_name: "Brain",
    severity: 6,
    notes: "",
    _seedDaysAgo: 15,
  },
  {
    symptom_name: "Fatigue",
    icon_name: "Bed",
    severity: 6,
    notes: "",
    _seedDaysAgo: 15,
  },
  {
    symptom_name: "Fatigue",
    icon_name: "Bed",
    severity: 7,
    notes: "",
    _seedDaysAgo: 15,
  },
  {
    symptom_name: "Stress",
    icon_name: "HeartPulse",
    severity: 5,
    notes: "",
    _seedDaysAgo: 15,
  },
  {
    symptom_name: "Stress",
    icon_name: "HeartPulse",
    severity: 6,
    notes: "",
    _seedDaysAgo: 15,
  },
  {
    symptom_name: "Poor Sleep",
    icon_name: "Moon",
    severity: 7,
    notes: "Woke up several times through the night.",
    _seedDaysAgo: 15,
  },
  {
    symptom_name: "Neck Pain",
    icon_name: "BicepsFlexed",
    severity: 6,
    notes: "",
    _seedDaysAgo: 15,
  },

  // 14 days ago
  {
    symptom_name: "Headache",
    icon_name: "Brain",
    severity: 8,
    notes: "Started right after waking up.",
    _seedDaysAgo: 14,
  },
  {
    symptom_name: "Headache",
    icon_name: "Brain",
    severity: 7,
    notes: "",
    _seedDaysAgo: 14,
  },
  {
    symptom_name: "Headache",
    icon_name: "Brain",
    severity: 9,
    notes: "",
    _seedDaysAgo: 14,
  },
  {
    symptom_name: "Headache",
    icon_name: "Brain",
    severity: 6,
    notes: "",
    _seedDaysAgo: 14,
  },
  {
    symptom_name: "Fatigue",
    icon_name: "Bed",
    severity: 7,
    notes: "Running on empty by mid morning.",
    _seedDaysAgo: 14,
  },
  {
    symptom_name: "Fatigue",
    icon_name: "Bed",
    severity: 8,
    notes: "",
    _seedDaysAgo: 14,
  },
  {
    symptom_name: "Fatigue",
    icon_name: "Bed",
    severity: 6,
    notes: "",
    _seedDaysAgo: 14,
  },
  {
    symptom_name: "Stress",
    icon_name: "HeartPulse",
    severity: 6,
    notes: "",
    _seedDaysAgo: 14,
  },
  {
    symptom_name: "Stress",
    icon_name: "HeartPulse",
    severity: 7,
    notes: "",
    _seedDaysAgo: 14,
  },
  {
    symptom_name: "Stress",
    icon_name: "HeartPulse",
    severity: 5,
    notes: "",
    _seedDaysAgo: 14,
  },
  {
    symptom_name: "Poor Sleep",
    icon_name: "Moon",
    severity: 8,
    notes: "Took hours to fall asleep.",
    _seedDaysAgo: 14,
  },
  {
    symptom_name: "Neck Pain",
    icon_name: "BicepsFlexed",
    severity: 7,
    notes: "Tight across the shoulders after a long day at the desk.",
    _seedDaysAgo: 14,
  },
  {
    symptom_name: "Brain Fog",
    icon_name: "Cloud",
    severity: 5,
    notes: "",
    _seedDaysAgo: 14,
  },
  {
    symptom_name: "Eye Strain",
    icon_name: "Eye",
    severity: 6,
    notes: "Screens felt harsh by the end of the day.",
    _seedDaysAgo: 14,
  },

  // 13 days ago
  {
    symptom_name: "Headache",
    icon_name: "Brain",
    severity: 9,
    notes: "Worst one this week, had to step away from work.",
    _seedDaysAgo: 13,
  },
  {
    symptom_name: "Headache",
    icon_name: "Brain",
    severity: 8,
    notes: "",
    _seedDaysAgo: 13,
  },
  {
    symptom_name: "Headache",
    icon_name: "Brain",
    severity: 7,
    notes: "",
    _seedDaysAgo: 13,
  },
  {
    symptom_name: "Headache",
    icon_name: "Brain",
    severity: 8,
    notes: "",
    _seedDaysAgo: 13,
  },
  {
    symptom_name: "Headache",
    icon_name: "Brain",
    severity: 9,
    notes: "",
    _seedDaysAgo: 13,
  },
  {
    symptom_name: "Fatigue",
    icon_name: "Bed",
    severity: 8,
    notes: "",
    _seedDaysAgo: 13,
  },
  {
    symptom_name: "Fatigue",
    icon_name: "Bed",
    severity: 7,
    notes: "",
    _seedDaysAgo: 13,
  },
  {
    symptom_name: "Fatigue",
    icon_name: "Bed",
    severity: 8,
    notes: "",
    _seedDaysAgo: 13,
  },
  {
    symptom_name: "Fatigue",
    icon_name: "Bed",
    severity: 6,
    notes: "",
    _seedDaysAgo: 13,
  },
  {
    symptom_name: "Stress",
    icon_name: "HeartPulse",
    severity: 7,
    notes: "Busy week catching up with me.",
    _seedDaysAgo: 13,
  },
  {
    symptom_name: "Stress",
    icon_name: "HeartPulse",
    severity: 8,
    notes: "",
    _seedDaysAgo: 13,
  },
  {
    symptom_name: "Stress",
    icon_name: "HeartPulse",
    severity: 6,
    notes: "",
    _seedDaysAgo: 13,
  },
  {
    symptom_name: "Poor Sleep",
    icon_name: "Moon",
    severity: 8,
    notes: "Maybe four hours total.",
    _seedDaysAgo: 13,
  },
  {
    symptom_name: "Neck Pain",
    icon_name: "BicepsFlexed",
    severity: 7,
    notes: "",
    _seedDaysAgo: 13,
  },
  {
    symptom_name: "Neck Pain",
    icon_name: "BicepsFlexed",
    severity: 6,
    notes: "",
    _seedDaysAgo: 13,
  },
  {
    symptom_name: "Brain Fog",
    icon_name: "Cloud",
    severity: 6,
    notes: "Kept losing my train of thought.",
    _seedDaysAgo: 13,
  },
  {
    symptom_name: "Eye Strain",
    icon_name: "Eye",
    severity: 7,
    notes: "",
    _seedDaysAgo: 13,
  },
  {
    symptom_name: "Nausea",
    icon_name: "Utensils",
    severity: 6,
    notes: "Skipped lunch, no appetite.",
    _seedDaysAgo: 13,
  },

  // 12 days ago
  {
    symptom_name: "Headache",
    icon_name: "Brain",
    severity: 8,
    notes: "Eased off a bit after some water and a break outside.",
    _seedDaysAgo: 12,
  },
  {
    symptom_name: "Headache",
    icon_name: "Brain",
    severity: 7,
    notes: "",
    _seedDaysAgo: 12,
  },
  {
    symptom_name: "Headache",
    icon_name: "Brain",
    severity: 9,
    notes: "",
    _seedDaysAgo: 12,
  },
  {
    symptom_name: "Fatigue",
    icon_name: "Bed",
    severity: 7,
    notes: "",
    _seedDaysAgo: 12,
  },
  {
    symptom_name: "Fatigue",
    icon_name: "Bed",
    severity: 6,
    notes: "",
    _seedDaysAgo: 12,
  },
  {
    symptom_name: "Stress",
    icon_name: "HeartPulse",
    severity: 8,
    notes: "Deadline pressure all day.",
    _seedDaysAgo: 12,
  },
  {
    symptom_name: "Stress",
    icon_name: "HeartPulse",
    severity: 7,
    notes: "",
    _seedDaysAgo: 12,
  },
  {
    symptom_name: "Stress",
    icon_name: "HeartPulse",
    severity: 9,
    notes: "",
    _seedDaysAgo: 12,
  },
  {
    symptom_name: "Stress",
    icon_name: "HeartPulse",
    severity: 6,
    notes: "",
    _seedDaysAgo: 12,
  },
  {
    symptom_name: "Poor Sleep",
    icon_name: "Moon",
    severity: 7,
    notes: "",
    _seedDaysAgo: 12,
  },
  {
    symptom_name: "Neck Pain",
    icon_name: "BicepsFlexed",
    severity: 6,
    notes: "",
    _seedDaysAgo: 12,
  },
  {
    symptom_name: "Eye Strain",
    icon_name: "Eye",
    severity: 6,
    notes: "",
    _seedDaysAgo: 12,
  },

  // 11 days ago - No entries

  // 10 days ago
  {
    symptom_name: "Headache",
    icon_name: "Brain",
    severity: 9,
    notes: "Throbbing, light made it worse.",
    _seedDaysAgo: 10,
  },
  {
    symptom_name: "Headache",
    icon_name: "Brain",
    severity: 8,
    notes: "",
    _seedDaysAgo: 10,
  },
  {
    symptom_name: "Headache",
    icon_name: "Brain",
    severity: 7,
    notes: "",
    _seedDaysAgo: 10,
  },
  {
    symptom_name: "Headache",
    icon_name: "Brain",
    severity: 8,
    notes: "",
    _seedDaysAgo: 10,
  },
  {
    symptom_name: "Fatigue",
    icon_name: "Bed",
    severity: 8,
    notes: "Needed a nap in the afternoon.",
    _seedDaysAgo: 10,
  },
  {
    symptom_name: "Fatigue",
    icon_name: "Bed",
    severity: 7,
    notes: "",
    _seedDaysAgo: 10,
  },
  {
    symptom_name: "Fatigue",
    icon_name: "Bed",
    severity: 8,
    notes: "",
    _seedDaysAgo: 10,
  },
  {
    symptom_name: "Fatigue",
    icon_name: "Bed",
    severity: 6,
    notes: "",
    _seedDaysAgo: 10,
  },
  {
    symptom_name: "Stress",
    icon_name: "HeartPulse",
    severity: 7,
    notes: "",
    _seedDaysAgo: 10,
  },
  {
    symptom_name: "Stress",
    icon_name: "HeartPulse",
    severity: 6,
    notes: "",
    _seedDaysAgo: 10,
  },
  {
    symptom_name: "Poor Sleep",
    icon_name: "Moon",
    severity: 8,
    notes: "",
    _seedDaysAgo: 10,
  },
  {
    symptom_name: "Neck Pain",
    icon_name: "BicepsFlexed",
    severity: 8,
    notes: "Stiff from the moment I woke up.",
    _seedDaysAgo: 10,
  },
  {
    symptom_name: "Neck Pain",
    icon_name: "BicepsFlexed",
    severity: 7,
    notes: "",
    _seedDaysAgo: 10,
  },
  {
    symptom_name: "Brain Fog",
    icon_name: "Cloud",
    severity: 7,
    notes: "Reread the same paragraph three times.",
    _seedDaysAgo: 10,
  },
  {
    symptom_name: "Eye Strain",
    icon_name: "Eye",
    severity: 7,
    notes: "",
    _seedDaysAgo: 10,
  },

  // 9 days ago
  {
    symptom_name: "Headache",
    icon_name: "Brain",
    severity: 8,
    notes: "",
    _seedDaysAgo: 9,
  },
  {
    symptom_name: "Headache",
    icon_name: "Brain",
    severity: 7,
    notes: "",
    _seedDaysAgo: 9,
  },
  {
    symptom_name: "Headache",
    icon_name: "Brain",
    severity: 6,
    notes: "",
    _seedDaysAgo: 9,
  },
  {
    symptom_name: "Fatigue",
    icon_name: "Bed",
    severity: 7,
    notes: "Tired even after sleeping in.",
    _seedDaysAgo: 9,
  },
  {
    symptom_name: "Fatigue",
    icon_name: "Bed",
    severity: 6,
    notes: "",
    _seedDaysAgo: 9,
  },
  {
    symptom_name: "Fatigue",
    icon_name: "Bed",
    severity: 8,
    notes: "",
    _seedDaysAgo: 9,
  },
  {
    symptom_name: "Stress",
    icon_name: "HeartPulse",
    severity: 6,
    notes: "",
    _seedDaysAgo: 9,
  },
  {
    symptom_name: "Stress",
    icon_name: "HeartPulse",
    severity: 5,
    notes: "",
    _seedDaysAgo: 9,
  },
  {
    symptom_name: "Poor Sleep",
    icon_name: "Moon",
    severity: 7,
    notes: "",
    _seedDaysAgo: 9,
  },
  {
    symptom_name: "Nausea",
    icon_name: "Utensils",
    severity: 7,
    notes: "Queasy after breakfast.",
    _seedDaysAgo: 9,
  },

  // 8 days ago - No entries

  // 7 days ago
  {
    symptom_name: "Headache",
    icon_name: "Brain",
    severity: 6,
    notes: "Milder than the last few days.",
    _seedDaysAgo: 7,
  },
  {
    symptom_name: "Headache",
    icon_name: "Brain",
    severity: 5,
    notes: "",
    _seedDaysAgo: 7,
  },
  {
    symptom_name: "Fatigue",
    icon_name: "Bed",
    severity: 5,
    notes: "",
    _seedDaysAgo: 7,
  },
  {
    symptom_name: "Fatigue",
    icon_name: "Bed",
    severity: 6,
    notes: "",
    _seedDaysAgo: 7,
  },
  {
    symptom_name: "Stress",
    icon_name: "HeartPulse",
    severity: 5,
    notes: "Calmer once the deadline passed.",
    _seedDaysAgo: 7,
  },
  {
    symptom_name: "Stress",
    icon_name: "HeartPulse",
    severity: 4,
    notes: "",
    _seedDaysAgo: 7,
  },
  {
    symptom_name: "Poor Sleep",
    icon_name: "Moon",
    severity: 6,
    notes: "Started winding down earlier, helped a little.",
    _seedDaysAgo: 7,
  },
  {
    symptom_name: "Neck Pain",
    icon_name: "BicepsFlexed",
    severity: 5,
    notes: "",
    _seedDaysAgo: 7,
  },
  {
    symptom_name: "Brain Fog",
    icon_name: "Cloud",
    severity: 5,
    notes: "",
    _seedDaysAgo: 7,
  },

  // 6 days ago
  {
    symptom_name: "Headache",
    icon_name: "Brain",
    severity: 4,
    notes: "Noticeable but manageable.",
    _seedDaysAgo: 6,
  },
  {
    symptom_name: "Headache",
    icon_name: "Brain",
    severity: 3,
    notes: "",
    _seedDaysAgo: 6,
  },
  {
    symptom_name: "Fatigue",
    icon_name: "Bed",
    severity: 4,
    notes: "",
    _seedDaysAgo: 6,
  },
  {
    symptom_name: "Stress",
    icon_name: "HeartPulse",
    severity: 3,
    notes: "",
    _seedDaysAgo: 6,
  },
  {
    symptom_name: "Poor Sleep",
    icon_name: "Moon",
    severity: 3,
    notes: "",
    _seedDaysAgo: 6,
  },
  {
    symptom_name: "Neck Pain",
    icon_name: "BicepsFlexed",
    severity: 4,
    notes: "Stretching in the morning seems to help.",
    _seedDaysAgo: 6,
  },

  // 5 days ago
  {
    symptom_name: "Headache",
    icon_name: "Brain",
    severity: 3,
    notes: "Brief, faded by the evening.",
    _seedDaysAgo: 5,
  },
  {
    symptom_name: "Stress",
    icon_name: "HeartPulse",
    severity: 2,
    notes: "",
    _seedDaysAgo: 5,
  },

  // 4 days ago
  {
    symptom_name: "Headache",
    icon_name: "Brain",
    severity: 3,
    notes: "",
    _seedDaysAgo: 4,
  },
  {
    symptom_name: "Headache",
    icon_name: "Brain",
    severity: 4,
    notes: "",
    _seedDaysAgo: 4,
  },
  {
    symptom_name: "Fatigue",
    icon_name: "Bed",
    severity: 4,
    notes: "",
    _seedDaysAgo: 4,
  },
  {
    symptom_name: "Fatigue",
    icon_name: "Bed",
    severity: 3,
    notes: "",
    _seedDaysAgo: 4,
  },
  {
    symptom_name: "Stress",
    icon_name: "HeartPulse",
    severity: 3,
    notes: "",
    _seedDaysAgo: 4,
  },
  {
    symptom_name: "Poor Sleep",
    icon_name: "Moon",
    severity: 2,
    notes: "Best night in a while.",
    _seedDaysAgo: 4,
  },
  {
    symptom_name: "Brain Fog",
    icon_name: "Cloud",
    severity: 3,
    notes: "",
    _seedDaysAgo: 4,
  },
  {
    symptom_name: "Eye Strain",
    icon_name: "Eye",
    severity: 4,
    notes: "Long stretch in front of the monitor.",
    _seedDaysAgo: 4,
  },
  {
    symptom_name: "Eye Strain",
    icon_name: "Eye",
    severity: 3,
    notes: "",
    _seedDaysAgo: 4,
  },

  // 3 days ago
  {
    symptom_name: "Fatigue",
    icon_name: "Bed",
    severity: 2,
    notes: "Energy dipped right after lunch.",
    _seedDaysAgo: 3,
  },
  {
    symptom_name: "Stress",
    icon_name: "HeartPulse",
    severity: 2,
    notes: "",
    _seedDaysAgo: 3,
  },
  {
    symptom_name: "Nausea",
    icon_name: "Utensils",
    severity: 3,
    notes: "Settled after eating something light.",
    _seedDaysAgo: 3,
  },

  // 2 days ago
  {
    symptom_name: "Headache",
    icon_name: "Brain",
    severity: 2,
    notes: "",
    _seedDaysAgo: 2,
  },
  {
    symptom_name: "Fatigue",
    icon_name: "Bed",
    severity: 3,
    notes: "Slow start but picked up.",
    _seedDaysAgo: 2,
  },
  {
    symptom_name: "Fatigue",
    icon_name: "Bed",
    severity: 2,
    notes: "",
    _seedDaysAgo: 2,
  },
  {
    symptom_name: "Stress",
    icon_name: "HeartPulse",
    severity: 2,
    notes: "",
    _seedDaysAgo: 2,
  },
  {
    symptom_name: "Poor Sleep",
    icon_name: "Moon",
    severity: 2,
    notes: "",
    _seedDaysAgo: 2,
  },
  {
    symptom_name: "Neck Pain",
    icon_name: "BicepsFlexed",
    severity: 3,
    notes: "",
    _seedDaysAgo: 2,
  },
  {
    symptom_name: "Brain Fog",
    icon_name: "Cloud",
    severity: 2,
    notes: "",
    _seedDaysAgo: 2,
  },

  // 1 day ago
  {
    symptom_name: "Headache",
    icon_name: "Brain",
    severity: 3,
    notes: "Came on late in the afternoon.",
    _seedDaysAgo: 1,
  },
  {
    symptom_name: "Headache",
    icon_name: "Brain",
    severity: 2,
    notes: "",
    _seedDaysAgo: 1,
  },
  {
    symptom_name: "Fatigue",
    icon_name: "Bed",
    severity: 3,
    notes: "",
    _seedDaysAgo: 1,
  },
  {
    symptom_name: "Stress",
    icon_name: "HeartPulse",
    severity: 3,
    notes: "",
    _seedDaysAgo: 1,
  },
  {
    symptom_name: "Stress",
    icon_name: "HeartPulse",
    severity: 2,
    notes: "",
    _seedDaysAgo: 1,
  },
  {
    symptom_name: "Brain Fog",
    icon_name: "Cloud",
    severity: 2,
    notes: "",
    _seedDaysAgo: 1,
  },
  {
    symptom_name: "Eye Strain",
    icon_name: "Eye",
    severity: 3,
    notes: "",
    _seedDaysAgo: 1,
  },
  {
    symptom_name: "Nausea",
    icon_name: "Utensils",
    severity: 2,
    notes: "",
    _seedDaysAgo: 1,
  },

  // Today
  {
    symptom_name: "Headache",
    icon_name: "Brain",
    severity: 8,
    notes: "Sharp flare-up this afternoon, worst one in over a week.",
    _seedDaysAgo: 0,
  },
  {
    symptom_name: "Stress",
    icon_name: "HeartPulse",
    severity: 6,
    notes: "Wound up once the headache set in.",
    _seedDaysAgo: 0,
  },
  {
    symptom_name: "Poor Sleep",
    icon_name: "Moon",
    severity: 3,
    notes: "",
    _seedDaysAgo: 0,
  },

];
